<?php
$h1="";
$link="";
include('includes/first_loaded.php');
$lang="fr";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
<title>Disclaimer</title>
<?php include('includes/meta.php');?>
</head> 
<body>
<div id="container">
	<?php include('includes/header.php');?>
	<div id="mct" class="ptop credit">
	<h1 style="display:none;"></h1>
		<h2>Disclaimer FR</h2>
		<p style="font-size:0.8em;line-height:1.4em;">Je prends connaissance du fait et accepte que Cashflex / Prestaflex-Services transmette ma demande à Cembra Money Bank, Bank Now, CreditGate24 ou tout autre établissement financier ou agence, ceci par Internet, e-mail, fax ou courrier. Je prends en particulier connaissance de ce qui suit.</p>
		<p style="font-size:0.8em;line-height:1.4em;">Examen de crédit et informations de crédit: je confirme que toutes mes informations fournies sont correctes et j'autorise la banque à se procurer des renseignements à mon sujet dans le cadre de l'examen de ma demande et de l'exécution de la relation contractuelle, par exemple auprès de banques, d'analystes de solvabilité extérieurs, d'offices publics, de la centrale d'information de crédit (ZEK), du centre de renseignement sur le crédit à la consommation (IKO) ou d'autres organismes prévus par la loi, ainsi qu'à notifier la ZEK, l'IKO ou d'autres organismes conformément au devoir prescript par la loi. Je reconnais à la ZEK et l'IKO le droit de rendre les données qui leur ont été notifiées accessibles à leurs membres. D'éventuels verrouillages de données décidés par moi-même à l'égard de la banque sont considérés comme levés. J'accepte que la banque et/ou ses partenaires contractuels (y compris les agents en crédit) procèdent à la consultation, au traitement et à l'enregistrement en Suisse et à l'étranger de certaines informations de crédit me concernant fournies dans ce contexte par des tiers, et notamment aussi celles fournies par la ZEK et l'IKO dans le cadre de l'examen de la demande de crédit et de l'exécution du contrat. Les partenaires contractuels et leurs collaborateurs sont tenus de respecter la protection des données conformément aux exigences de la Loi fédérale sur la protection des données, le secret bancaire confomément à la loi fédérale sur les banques ainsi que le principe de confidentialité.</p>
		<p style="font-size:0.8em;line-height:1.4em;">Données personnelles et protection des données: j'autorise la banque à traiter et analyser mes données, de même qu'à les utiliser à des fins de marketing et d'analyses internes en Suisse et à l'étranger. Je suis en droit de révoquer cette autorisation en tout temps. La banque peut déléguer des prestations à des tiers ("prestataires"), en particulier dans les domaines du déroulement de processus, de la sécurité informatique, de la gestion de systèmes, de prospection et d'études de marché, du calcul de risques de crédit et de marché lié aux affaires, de même que la gestion de relations contractuelles (par ex. traitement de la demande et exécution du contrat, recouvrement, communication avec les clients). J'accepte que des prestataires aient accès à toutes mes données traitées dans ce cadre. La banque peut faire traiter mes données dans des états qui ne disposent pas d'une protection des données équivalente à celle de la Suisse et charger des prestataires de tels Etats de traiter mdes donnéées. Ces données ne sont transmises que si ces prestataires se sont engagés au préalable à fournir un niveau adéquat de protection des données. Je suis conscient que mes données peuvent être transmises à l'étranger et que cela se fera aussi par Internet. J'accepte ce type de transmission de données ainsi que leur traitement en Suisse et à l'étranger. La banque a le droit de refuser la présente demande sans en indiquer les raisons. Je suis conscient qu'Internet est un réseau ouvert accessible à tous. En conséquence, Cashflex , PrestaFlex-serve ou la banque ne peuvent pas garantir la confidentialité des données transmises par Internet. Les conclusions de tiers sur une relation bancaire existant ou sur le point d'exister entre moi-même et la banque sont donc possibles.</p>
		<p style="font-size:0.8em;line-height:1.4em;">Transmission des données: j'accepte également que mes informations soient transmises à d'autres partenaires dans une démarche de prospection, que ce soit par e-mail, par téléphone ou par tout autre moyen.</p>
		<p style="font-size:0.8em;line-height:1.4em;">Accord: Je confirme par la présente avoir pris connaissance de ce disclaimer dans son intégralité et déclare en accepter tous les points.</p>
		<p style="font-size:0.8em;line-height:1.4em;">Au sens de la loi, l'octroi d'un crédit est interdit s'il occasionne le surendettement du consommateur (art. 3 LCD)</p>
		<hr>
		<h2>Disclaimer DE</h2>
		<p style="font-size:0.8em;line-height:1.4em;">Disclaimer: Ich nehme zur Kenntnis und willige ein, dass Cashflex Multicredit Gmbh / Prestaflex-Services GMBH meinen Antrag an die Cembra Money Bank AG, CreditGate24 oder andere Banken (je einzeln nachfolgend die "Bank") über das Internet, via Email oder per Fax/Post weiterleitet. Insbesondere nehme ich zur Kenntnis.</p>
		 <p style="font-size:0.8em;line-height:1.4em;">Kreditprüfung und Kreditauskunftsdaten: Ich bestätige die Richtigkeit aller meiner Angaben und ermächtige die Bank, im Zusammenhang mit der Prüfung dieses Antrags und der Abwicklung der vertraglichen Beziehung über mich Auskünfte, z.B. bei Banken, externen Bonitätsprüfern, staatlichen Stellen, der Zentralstelle für Kreditinformation (ZEK), der Informationsstelle für Konsumkredit (IKO) und weiteren vom Gesetz vorgesehenen oder anderen Stellen, einzuholen sowie der ZEK, der IKO und bei entsprechenden gesetzlichen Pflichten auch anderen Stellen Meldung zu erstatten. Ich anerkenne das Recht der ZEK und der IKO, ihren Mitgliedern über die gemeldeten Daten Auskünfte zu erteilen. Allfällige von mir verfügte Datensperren gelten gegenüber der Bank als aufgehoben. Ich bin damit einverstanden, dass gewisse der in diesem Zusammenhang bei Dritten über mich eingeholten Kreditauskunftsdaten und namentlich auch diejenigen der ZEK und der IKO im Zusammenhang mit der Antragsprüfung und Vertragsabwicklung von der Bank und/oder deren Vertragspartnern (einschliesslich Vermittlern) im In- und Ausland abgerufen, bearbeitet und gespeichert werden. Vertragspartner und deren Mitarbeiter sind dabei zur Einhaltung des Datenschutzes gemäss den Anforderungen des schweizerischen Datenschiatzgesetzes, zur Wahrung des Bankkundengeheimnisses entsprechend dem schweizerischen Bankengesetz und zur Vertraulichkeit verpflichtet.</p>
		 <p style="font-size:0.8em;line-height:1.4em;">Datenübertragung: Ich stimme auch zu, dass meine Daten auch an andere Partner per Email, Telefon oder auf andere Art und Weise weitergegeben werden dürfen. Ich weiss auch, dass das Internet ein Medium der Kommunikation ist und für alle zugänglich ist. Emails, die über das Internet gesendet werden, sind weder vertraulich noch sicher. Sie könnten von Dritte gelesen, verloren, abgefangen oder verändert werden. Emails übergehen Grenzen, auch wenn sich der Absender und der Empfänger im gleichen Land befinden. Cashflex Gmbh haftet nicht für gesendete Nachrichten oder andere elektronische Nachrichten-Systeme.</p>
		 <p style="font-size:0.8em;line-height:1.4em;">Persönliche Daten und Datenschutz: Ich ermächtige die Bank, meine Daten zu bearbeiten und auszuwerten sowie zu Marketingzwecken und - auswertungen im In- und Ausland zu verwenden. Ich kann diese Ermächtigung jederzeit widerrufen. Die Bank kann Dienstleistungen an Dritte auslagern ("Dienstleister"), insbesondere im Bereich Abwicklung von Geschäftsprozessen, ITSicherheit und Systemsteuerung, Marktforschung und -bearbeitung, der Berechnung von geschäftsrelevanten Kreditund Marktrisiken sowie der Administration von Vertragsverhältnissen (z.B. Antrags- und Vertragsabwicklung, Inkasso, Kommunikation mit Kunden). Ich bin damit einverstanden, dass Dienstleister Zugriff auf alle meine Daten haben, welche in diesem Rahmen bearbeitet werden. Die Bank kann meine Daten in Staaten bearbeiten lassen, die über keinen gleichwertigen Datenschutz wie die Schweiz verfügen, und Dienstleister in solchen Staaten mit der Bearbeitung meiner Daten beauftragen. Eine Weitergabe der Daten erfolgt nur, wenn sich die Dienstleister vorgängig zu einem angemessenen Datenschutzniveau verpflichtet haben. Ich bin mir bewusst, dass meine Daten ins Ausland übermittelt und auch über das Internet übertragen werden können. Ich akzeptiere solche Übermittlungen und Bearbeitungen im Inund Ausland. Die Bank hat das Recht, den vorliegenden Antrag ohne Angabe von Gründen abzulehnen. Mir ist bewusst, dass das Internet ein offenes, für jedermann zugängliches Netz darstellt. Entsprechend können [Name/ Firma Vermittler] sowie die Bank die Vertraulichkeit von Daten bei der Übertragung über das Internet nicht gewährleisten. Rückschlüsse Dritter auf eine zwischen mir und der Bank bestehende bzw. bevorstehende Bankbeziehung sind daher möglich.</p>
		 <p style="font-size:0.8em;line-height:1.4em;">Klausel: In dem Fall, dass eine Bestimmung dieser Nutzungsbedingungen als ungültig, illegal oder nicht durchsetzbar im Gesetz oder der zuständigen Gerichtsbarkeit erklärt wird, so ist diese Bestimmung als nicht Teil dieses Haftungsausschlusses. Diese Schlussfolgerung sollte jedoch keinen Einfluss auf die Gültigkeit, Rechtmässigkeit und Durchsetzbarkeit der übrigen Bestimmungen dieser Nutzungsbedingungen haben.</p>
		 <p style="font-size:0.8em;line-height:1.4em;">Die Kreditvergabe ist verboten, wenn sie zu Verschuldung der Verbraucher führt (art. 3 UWG).</p>
	</div>
	<?php include('includes/footer.php');?>
	<?php include('includes/last.php');?>
</div>
</body>
</html>
